export const ErrorCodes = {
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Not Found
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',

  // Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Business Logic
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVALID_STATE: 'INVALID_STATE',
  CONFLICT: 'CONFLICT',

  // Infrastructure
  PERSISTENCE_ERROR: 'PERSISTENCE_ERROR',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  LOCKED: 'LOCKED',
  TIMEOUT: 'TIMEOUT',
  COMMIT_ERROR: 'COMMIT_ERROR',
  COMMIT_FAILED: 'COMMIT_FAILED',
  INVARIANT_VIOLATION: 'INVARIANT_VIOLATION',
};
